# Generated by Django 3.2.9 on 2022-06-27 20:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, editable=['%Y-%d-%m'])),
                ('email', models.EmailField(blank=True, max_length=256)),
                ('idNumber', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=12), blank=True, size=None)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('probability', models.FloatField(blank=True)),
            ],
        ),
    ]
