# Generated by Django 3.2.9 on 2022-06-28 19:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, default=None, editable=['%Y-%d-%m'], null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=256, null=True)),
                ('idNumber', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('phone', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=12, null=True), blank=True, default=None, null=True, size=None)),
                ('grade', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('probability', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
