# Generated by Django 3.2.9 on 2022-06-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateTimeField(null=True)),
                ('email', models.EmailField(max_length=256, null=True)),
                ('idNumber', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('grade', models.CharField(max_length=2)),
                ('probability', models.FloatField()),
            ],
        ),
    ]
