# Generated by Django 3.2.9 on 2022-06-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(editable=['%Y-%d-%m'], null=True),
        ),
    ]
