# Generated by Django 3.2.9 on 2022-06-25 08:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(editable=['%Y-%d-%m'], null=True)),
                ('email', models.EmailField(max_length=256, null=True)),
                ('idNumber', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(editable=['%Y-%d-%m'], null=True)),
                ('idNumber', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=12, null=True), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2)),
                ('probability', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
